# Generated by Django 2.2.6 on 2019-10-23 00:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, max_length=500)),
                ('sidenote', models.TextField(blank=True, max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
